- name: Install libssl1.1
  shell: |
    wget http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1n-0+deb10u3_amd64.deb
    dpkg -i libssl1.1_1.1.1n-0+deb10u3_amd64.deb
  args:
    creates: /usr/lib/x86_64-linux-gnu/libssl.so.1.1


# 3. Zainstaluj MongoDB
- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Add MongoDB repository
  copy:
    content: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"
    dest: /etc/apt/sources.list.d/mongodb-org-6.0.list

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

# 4. Uruchom MongoDB
- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes