- name: Ensure project directory exists
  file:
    path: /var/www/server
    state: directory
    mode: '0755'

- name: Initialize Terraform
  command: terraform init
  args:
    chdir: /var/www/server

- name: Plan Terraform
  command: terraform plan -out=plan.out -var="docker_image=node:23"
  args:
    chdir: /var/www/server
  register: terraform_plan

- name: Display Terraform plan
  debug:
    msg: "Plan: \n{{ terraform_plan.stdout }}"

- name: Apply Terraform
  command: terraform apply -auto-approve plan.out
  args:
    chdir: /var/www/server
  register: terraform_apply

- name: Display Terraform apply
  debug:
    msg: "Apply: \n{{ terraform_apply.stdout }}"