name: "Automated Node.js app with MongoDB and terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build&Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t node-mongo-app .
          docker run -d --name mongo mongo:5.0
          docker run -d --name app --link mongo -p 3000:3000 node-mongo-app
          sleep 10
          curl http://localhost:3000 || exit 1

      - name: Push to DockerHub
        run: |
          docker tag node-mongo-app ${{ secrets.DOCKER_USERNAME }}/node-mongo-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/node-mongo-app:latest

  deploy:
    name: Deploy using terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Run Terraform on VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /path/to/terraform/directory
            terraform init
            terraform plan 
            terraform apply -auto-approve
            terraform destroy -auto-approve
          EOF